# Project Information
site_name: CodeMonster Wiki
site_description: CodeMonster Wiki
site_author: CodeMonster Wiki Team




#Theme
theme: slate

# Copyright
copyright: 'Copyright &copy; 2019 CodeMonster'
